<a href="https://colab.research.google.com/github/Chandrakanth9394/DATA-SCIENCE-LAB/blob/main/naivebayesiris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset=pd.read_csv('/content/iris.csv')

In [3]:
dataset

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
scaler=StandardScaler()

In [6]:
scaler.fit(dataset.drop('species',axis=1))

StandardScaler()

In [7]:
dataset.columns[:-1]

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [9]:
scaled_features=scaler.transform(dataset.drop('species',axis=1))

In [10]:
scaled_features

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [11]:
new_dataset=pd.DataFrame(scaled_features,columns=dataset.columns[:-1])

In [12]:
new_dataset

sepal_length  sepal_width  petal_length  petal_width
0       -0.900681     1.032057     -1.341272    -1.312977
1       -1.143017    -0.124958     -1.341272    -1.312977
2       -1.385353     0.337848     -1.398138    -1.312977
3       -1.506521     0.106445     -1.284407    -1.312977
4       -1.021849     1.263460     -1.341272    -1.312977
..            ...          ...           ...          ...
145      1.038005    -0.124958      0.819624     1.447956
146      0.553333    -1.281972      0.705893     0.922064
147      0.795669    -0.124958      0.819624     1.053537
148      0.432165     0.800654      0.933356     1.447956
149      0.068662    -0.124958      0.762759     0.790591

[150 rows x 4 columns]

In [14]:
from sklearn.model_selection import train_test_split
X=new_dataset
y=dataset['species']

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [17]:
from sklearn.naive_bayes import GaussianNB , BernoulliNB, CategoricalNB

In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
scores=[]

In [21]:
classifier=GaussianNB()

In [22]:
classifier.fit(X_train,y_train)

GaussianNB()

In [23]:
y_pred=classifier.predict(X_test)

In [24]:
scores.append(accuracy_score(y_test,y_pred))

In [26]:
cm=confusion_matrix(y_test,y_pred)

In [27]:
cm

array([[19,  0,  0],
       [ 0, 12,  1],
       [ 0,  0, 13]])

In [28]:
print(scores)

[0.9777777777777777]


In [29]:
classifier1=BernoulliNB()

In [31]:
classifier1.fit(X_train,y_train)
y_pred=classifier1.predict(X_test)
scores.append(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
cm


array([[19,  0,  0],
       [ 0,  4,  9],
       [ 0,  1, 12]])

In [32]:
print(scores)

[0.9777777777777777, 0.7777777777777778, 0.7777777777777778]
