In [4]:
import numpy as kk
a=[1,2,3,4,5]
array=kk.array(a)
print(array)
b=([1,2,3],[4,5,6],[7,8,9],[10,11,12])
array1=kk.array(b)
print(array1)

[1 2 3 4 5]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
kk.arange(1,20)
kk.arange(1,30,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [9]:
kk.zeros(4)
kk.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
kk.ones(4)
kk.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
kk.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
a=kk.ones((3,3))
a=a.astype(int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [18]:
kk.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [20]:
kk.random.rand(5)
kk.random.randn(5)

array([ 1.03185196, -0.15972013,  0.28622668,  0.22477059,  0.76598161])

In [22]:
kk.random.rand(4,4)

array([[0.37031884, 0.10080427, 0.72179428, 0.46096545],
       [0.62222442, 0.42790777, 0.62744908, 0.35940326],
       [0.45882537, 0.99938389, 0.61133337, 0.35014596],
       [0.11725816, 0.99548689, 0.14379528, 0.87582811]])

In [24]:
kk.random.randint(1,100)

21

In [26]:
kk.random.randint(1,100,10)

array([17, 88, 80, 89, 18, 13, 92, 59,  5, 90])

In [32]:
a=kk.random.randint(1,100,10)
print(a)
a.reshape(5,2)
a.shape
a.max()

[28 51 22 10 93 42 50 62 29 52]


93

In [34]:
a.argmax()

4

In [37]:
a.min()


10

In [38]:
a.argmin()

3

In [43]:
a=kk.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a[0:3]

array([0, 1, 2])

In [48]:
a[:3]

array([0, 1, 2])

In [53]:
b=kk.array([[1,2,3],[4,5,6],[7,8,9],[10,22,11]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 22, 11]])

In [58]:
b[3][1]
b[0][0]
b[:2,1:]
b[:3,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [60]:
hello=kk.arange(5,15)
hello

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
hello>8


array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [63]:
hello[hello>8]

array([ 9, 10, 11, 12, 13, 14])